name: job_sept21

dependencies:
    - python==3.8
    - pip==21.2.2
    - xgboost
    - lightgbm
    - ipykernel


    - pip:
      - numpy
      - pandas
      - matplotlib
      - tensorflow
      - scikit-learn 
      - jupyterlab
      - optuna
      - seaborn
      - catboost
  
